### ISSUE TITLE
Reflect is pretty bulky but there is another way

### ISSUE THREAD

**Issue by wade-welles** [franpog859/index#8]
You should check out the reflect implementations that cut out large parts of the library, particularly the unsafe stuff that is specifically there for debugging. Your code footprint would shrink, the application security would be improved. if one does not exist that cuts out the right peices, if this library is worth while for you Id recommend doing it yourself. 

Just a consideration. Best of luck

**Comment by franpog859** [comment]
Thanks, @wade-welles ! I will definetely check it out 😄
